// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "skillRunnerEndpoint": string;
      "backendsConfigJson": string;
      "workflowSettingsJson": string;
      "workflowDir": string;
      "sampleOutputDir": string;
    };
  }
}
